[package]
name = "minigrep"
version = "0.1.0"
authors = ["Ace Eldeib <alexeldeib@gmail.com>"]
edition = "2018"

[lib]
name = "minigrep"
path = "src/lib.rs"

# [[bin]]
# name = "bin"
# path = "src/main.rs"
